baseURL = "https://tech.515hikaru.net"
languageCode = "ja-jp"
title = "I Was Perfect"
# Uncomment below to enable theme
theme = "vanilla-bootstrap-hugo-theme"
# googleAnalytics = "UA-123456789-1"

# Uncomment below to enable syntax highlighting
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/post/"
    weight = 2
  [[menu.main]]
    name = "About"
    pre = "smile"
    url = "/about/"
    weight = 3
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 4
  [[menu.main]]
    name = "RSS"
    pre = "rss"
    url = "/index.xml"
    weight = 5

[params]
  includeBootstrapJs = false
  showActiveNav = true
  containerMaxWidth = "700px"
  dateFormat = "Jan 2, 2006"
  homeText = """
  [Takahiro Kojima(a.k.a. 515hikaru)](https://github.com/515hikaru/) のメモ帳です。

  [About](/about): 自己紹介

  [Blog](/post): 記事一覧

  Mail: 12kojima.takahiro[at]gmail.com

  Twitter: [@515hikaru](https://twitter.com/515hikaru)

  GitHub: [@515hikaru](https://github.com/515hikaru)

  Qiita: [@515hikaru](https://qiita.com/515hikaru)
  """
  footerText = "Copyright 2017 Takahiro Kojima All Rights Reserved."
